In [1]:
import nltk
from collections import defaultdict
f


IndentationError: expected an indented block (<ipython-input-1-882bca212b9a>, line 31)

In [24]:
import json
with open ("abstract_dict.txt", "r") as myfile:
    data=myfile.readlines()
    d = json.loads(data[0])
    print(d)
   

{'23143855': 'This study provided a yearly record of consonant development for the initial 4 years of cochlear implant (CI) use and established a precedent for using a standardized articulation test, the Goldman-Fristoe Test of Articulation-2 (Goldman, R., & Fristoe, M. [2000]. Goldman-Fristoe Test of Articulation-2. Circle Pines, MN: American Guidance Services). The study used CI age as a referent for 32 children who received their CI before 30 months of age. Consonants produced by 70% of the children were listed, as were the most common error types, which were consonant omissions and substitutions. Using consonant repertoire lists and standard scores, the study revealed that children with CIs had acquisition patterns that were similar to their peers when the duration of CI experience was similar to the chronological age norms of typically developing children. The results revealed that CI users need time to coordinate their articulatory organizing principles with the input they receiv

In [25]:
import nltk
nltk.download('averaged_perceptron_tagger')
text = ''.join(d.values())
for idx, s in enumerate(nltk.sent_tokenize(text)): # Segmentation
    words = nltk.wordpunct_tokenize(s)  # Tokenization
    tags  = nltk.pos_tag(words)    # Part of Speech tagging
    print (tags)
    if idx > 5:
        break

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\MissBleu\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[('This', 'DT'), ('study', 'NN'), ('provided', 'VBD'), ('a', 'DT'), ('yearly', 'JJ'), ('record', 'NN'), ('of', 'IN'), ('consonant', 'NN'), ('development', 'NN'), ('for', 'IN'), ('the', 'DT'), ('initial', 'JJ'), ('4', 'CD'), ('years', 'NNS'), ('of', 'IN'), ('cochlear', 'JJ'), ('implant', 'NN'), ('(', '('), ('CI', 'NNP'), (')', ')'), ('use', 'NN'), ('and', 'CC'), ('established', 'VBD'), ('a', 'DT'), ('precedent', 'NN'), ('for', 'IN'), ('using', 'VBG'), ('a', 'DT'), ('standardized', 'JJ'), ('articulation', 'NN'), ('test', 'NN'), (',', ','), ('the', 'DT'), ('Goldman', 'NNP'), ('-', ':'), ('Fristoe', 'NNP'), ('Test', 'NNP'), ('of', 'IN'), ('Articulation', 'NNP'), ('-', ':'), ('2', 'CD'), ('(', '('), ('Goldman', 'NNP'), (',', ','), ('R', 'NNP'), ('.,', 'NNP'), ('&', 'CC'), ('Fris

In [64]:
from nltk import FreqDist
from nltk import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

vocab = FreqDist()
words = FreqDist()
for s in nltk.sent_tokenize(text): 
    for word in nltk.wordpunct_tokenize(s):
        words[word] += 1
        lemma = lemmatizer.lemmatize(word)
        vocab[lemma] += 1

print(words)
print(vocab)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\MissBleu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.
<FreqDist with 6461 samples and 35616 outcomes>
<FreqDist with 5998 samples and 35616 outcomes>


In [78]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit_transform(data)
smatrix = vectorizer.transform(data)
print(smatrix)



[[2 2 1 ..., 1 2 4]]


In [82]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(smatrix)
print ("IDF:", tfidf.idf_)
tf_idf_matrix = tfidf.transform(smatrix)
print (tf_idf_matrix.todense())

IDF: [ 1.  1.  1. ...,  1.  1.  1.]
[[ 0.00079008  0.00079008  0.00039504 ...,  0.00039504  0.00079008
   0.00158016]]


In [97]:
#Loading the data set - training data.
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train', shuffle=True)

# Extracting features from text files
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape

# TF-IDF
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape
# Machine Learning
# Training Naive Bayes (NB) classifier on training data.
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

In [98]:
from sklearn.pipeline import Pipeline

text_clf = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])

text_clf = text_clf.fit(twenty_train.data, twenty_train.target)

In [99]:
import numpy as np
twenty_test = fetch_20newsgroups(subset='test', shuffle=True)
predicted = text_clf.predict(twenty_test.data)
np.mean(predicted == twenty_test.target)

0.7738980350504514

In [84]:


import pandas as pd
import numpy as np
import gzip
import datetime
from collections import Counter
from collections import defaultdict
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



In [93]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit(data)
X_train_counts.shape

AttributeError: 'CountVectorizer' object has no attribute 'shape'

# And this is where it gets good

In [7]:
#nimh ninds
import pandas as pd
NIF = pd.read_csv("NIFSTD.csv", dtype = object)
keepCols = ["Preferred Label", "Synonyms", "Definitions"]
nif = str(NIF[keepCols])
nif

'                                          Preferred Label  \\\n0                                              narcolepsy   \n1       Venous varicosities of celiac and mesenteric v...   \n2                                    Olfactory perception   \n3       protein-DNA complex transmembrane transporter ...   \n4                            fumagillin metabolic process   \n5                                            Raphignathae   \n6       positive regulation of IRE1-mediated unfolded ...   \n7       peptidyl-aspartic acid reduction to form L-asp...   \n8                                       obsolete telomere   \n9       negative regulation of planar cell polarity pa...   \n10           rho/Cdc42/Rac GTPase-activating protein RICS   \n11      positive regulation of the force of heart cont...   \n12                                            XPC complex   \n13                           oculomotor nerve development   \n14                           corpus cavernosum maxillaris   \n15    

In [10]:
import nltk
import json
stopwords = ['a', 'an', 'and', 'are', 'as', 'be', 'by', 'for', 'from', 'has', 'he', 'i', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the', 'to', 'was', 'were', 'will', 'with']

def cleanDoc(doc):
    stopset = set(stopwords)
    stemmer = nltk.PorterStemmer()
    for idx, s in enumerate(nltk.sent_tokenize(doc)): # Segmentation
          # Tokenization
        tokens = nltk.wordpunct_tokenize(s) 
    clean = [token.lower() for token in tokens if token.lower() not in stopset and len(token) > 2]
    final = [stemmer.stem(word) for word in clean]
    return final

clean = cleanDoc(nif)

with open ('clean.text', 'w') as outfile:
    json.dumps(clean, outfile)
len(clean)

78

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit_transform(clean)
smatrix = vectorizer.transform(clean)
print(smatrix)

  (0, 17)	1
  (1, 21)	1
  (2, 23)	1
  (4, 0)	1
  (5, 34)	1
  (6, 1)	1
  (7, 31)	1
  (8, 45)	1
  (9, 32)	1
  (10, 40)	1
  (11, 28)	1
  (13, 2)	1
  (14, 25)	1
  (15, 41)	1
  (16, 38)	1
  (17, 43)	1
  (19, 3)	1
  (20, 36)	1
  (21, 27)	1
  (22, 17)	1
  (23, 21)	1
  (25, 4)	1
  (26, 40)	1
  (27, 48)	1
  (28, 39)	1
  :	:
  (48, 46)	1
  (49, 22)	1
  (50, 29)	1
  (52, 12)	1
  (53, 35)	1
  (54, 20)	1
  (55, 49)	1
  (56, 37)	1
  (57, 42)	1
  (59, 13)	1
  (60, 24)	1
  (61, 41)	1
  (62, 47)	1
  (63, 30)	1
  (65, 14)	1
  (66, 40)	1
  (67, 48)	1
  (68, 39)	1
  (70, 15)	1
  (71, 40)	1
  (72, 48)	1
  (73, 39)	1
  (75, 16)	1
  (76, 44)	1
  (77, 26)	1


In [16]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(smatrix)
print ("IDF:", tfidf.idf_)
tf_idf_matrix = tfidf.transform(smatrix)
print (tf_idf_matrix.todense())

IDF: [4.67630067 4.67630067 4.67630067 4.67630067 4.67630067 4.67630067
 4.67630067 4.67630067 4.67630067 4.67630067 4.67630067 4.67630067
 4.67630067 4.67630067 4.67630067 4.67630067 4.67630067 4.27083556
 4.67630067 4.67630067 4.67630067 4.27083556 4.67630067 4.67630067
 4.27083556 4.67630067 4.67630067 4.67630067 4.67630067 4.67630067
 4.67630067 4.67630067 4.67630067 4.67630067 3.4235377  4.67630067
 4.67630067 4.67630067 4.67630067 3.98315349 3.76000994 3.98315349
 4.67630067 4.67630067 4.67630067 4.67630067 4.67630067 4.67630067
 3.98315349 4.67630067]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
import gensim
from gensim import corpora, models, similarities
def makeText(textFile):
    dictionary = corpora.Dictionary(line.lower().split() for line in open(textFile))
    with open ('dictionary.text', 'w') as outfile:
        json.dumps(dictionary, outfile)
    return dictionary
NIFont = makeText(clean)



TypeError: invalid file: ['aggreg', 'arrang', 'bon', '...', '163332', 'nan', '163333', 'heat', 'shock', 'kda', 'protein', 'encod', '...', '163334', 'chemic', 'reaction', 'pathway', 'result', '...', '163335', 'non', 'coval', 'aggreg', 'arrang', '...', '163336', 'protein', 'translat', 'product', '...', '163337', 'nan', '163338', 'nan', '163339', 'nan', '163340', 'nan', '163341', 'catalysi', 'reaction', 'amino', 'methyl', '...', '163342', 'nan', '163343', 'ani', 'substanc', 'bodi', 'expel', '...', '163344', 'neural', 'arch', 'weberian', 'ossicl', 'reduc', '...', '163345', 'catalysi', 'reaction', 'sulfit', 'ferrici', '...', '163346', 'protein', 'translat', 'product', '...', '163347', 'protein', 'translat', 'product', '...', '163348', 'row', 'column']

In [69]:
import pandas as pd
import json
filenames = ['master_dict.txt', 'master_dict2.txt']
for fname in filenames:
    with open(fname) as infile:
        data=infile.readlines()
    myfile.close
    print("closed")


closed
closed


In [70]:
brain = str(data)
import nltk
import json
stopwords = ['a', 'an', 'and', 'are', 'as', 'be', 'by', 'for', 'from', 'has', 'he', 'i', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the', 'to', 'was', 'were', 'will', 'with']

def cleanDoc(doc):
    stopset = set(stopwords)
    stemmer = nltk.PorterStemmer()
    for idx, s in enumerate(nltk.sent_tokenize(doc)): # Segmentation
          # Tokenization
        tokens = nltk.wordpunct_tokenize(s) 
    clean = [token.lower() for token in tokens if token.lower() not in stopset and len(token) > 2]
    finalBr = [stemmer.stem(word) for word in clean]
    return finalBr

cleanBr1 = cleanDoc(brain)

with open ('cleanBr1.text', 'w') as outfile:
    json.dumps(cleanBr1, outfile)
len(cleanBr1)

18

In [71]:
import pandas as pd
import json
filenames = ['master_dict3.txt', 'master_dict4.txt']
for fname in filenames:
    with open(fname) as infile:
        alldata=infile.readlines()
    myfile.close
    print("closed")

closed
closed


In [72]:
noBrain = str(alldata)
import nltk
import json
stopwords = ['a', 'an', 'and', 'are', 'as', 'be', 'by', 'for', 'from', 'has', 'he', 'i', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the', 'to', 'was', 'were', 'will', 'with']

def cleanDoc(doc):
    stopset = set(stopwords)
    stemmer = nltk.PorterStemmer()
    for idx, s in enumerate(nltk.sent_tokenize(doc)): # Segmentation
          # Tokenization
        tokens = nltk.wordpunct_tokenize(s) 
    clean = [token.lower() for token in tokens if token.lower() not in stopset and len(token) > 2]
    finalBr = [stemmer.stem(word) for word in clean]
    return finalBr

other = cleanDoc(noBrain)

with open ('other.text', 'w') as outfile:
    json.dumps(other, outfile)
len(other)

19

In [73]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit_transform(cleanBr1)
smatrix = vectorizer.transform(cleanBr1)
print(smatrix)

  (0, 15)	1
  (1, 1)	1
  (2, 3)	1
  (3, 5)	1
  (4, 7)	1
  (5, 11)	1
  (6, 4)	1
  (7, 6)	1
  (8, 9)	1
  (9, 8)	1
  (10, 14)	1
  (11, 0)	1
  (12, 2)	1
  (13, 12)	1
  (14, 10)	1
  (15, 13)	1
  (16, 11)	1


In [74]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(smatrix)
print ("IDF:", tfidf.idf_)
tf_idf_matrix = tfidf.transform(smatrix)
print (tf_idf_matrix.todense())

IDF: [3.2512918  3.2512918  3.2512918  3.2512918  3.2512918  3.2512918
 3.2512918  3.2512918  3.2512918  3.2512918  3.2512918  2.84582669
 3.2512918  3.2512918  3.2512918  3.2512918 ]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [78]:
import string
import collections
 
from nltk import word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from pprint import pprint

stopwords = ['a', 'an', 'and', 'are', 'as', 'be', 'by', 'for', 'from', 'has', 'he', 'i', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the', 'to', 'was', 'were', 'will', 'with']

 
def process_text(text, stem=True):
    """ Tokenize text and stem words removing punctuation """
    text = text.translate(None, string.punctuation)
    tokens = word_tokenize(text)
 
    if stem:
        stemmer = PorterStemmer()
        tokens = [stemmer.stem(t) for t in tokens]
 
    return tokens
 
def cluster_texts(texts, clusters=3):
    ####Transform texts to Tf-Idf coordinates and cluster texts using K-Means """
    vectorizer = TfidfVectorizer(tokenizer=process_text,
                                 stop_words=stopwords,
                                 max_df=0.5,
                                 min_df=0.1,
                                 lowercase=True)
     tfidf_model = vectorizer.fit_transform(texts)
    km_model = KMeans(n_clusters=clusters)
    km_model.fit(tfidf_model)
 
    clustering = collections.defaultdict(list)
 
    for idx, label in enumerate(km_model.labels_):
        clustering[label].append(idx)
 
    return clustering
 
if __name__ == "__main__":
    articles = [brain]
    clusters = cluster_texts(articles, 7)
    pprint(dict(clusters))

process_text(brain, stem = True)
cluster_texts(brain, clusters = 3)

IndentationError: unexpected indent (<ipython-input-78-2d48883103a5>, line 32)